/gate/geometry/setMaterialDatabase GateMaterials.db

/gate/world/geometry/setXLength 2000. mm
/gate/world/geometry/setYLength 2000. mm
/gate/world/geometry/setZLength 2000. mm
/gate/world/vis/forceWireframe 1
/gate/world/vis/forceSolid 0
/gate/world/vis/setColor white
/gate/world/setMaterial Vacuum

/gate/world/daughters/name cylindricalPET
/gate/world/daughters/insert cylinder
/gate/cylindricalPET/setMaterial Vacuum
/gate/cylindricalPET/geometry/setRmin 409.0 mm
/gate/cylindricalPET/geometry/setRmax 500.0 mm
/gate/cylindricalPET/geometry/setHeight 1060 mm
/gate/cylindricalPET/vis/forceWireframe
/gate/cylindricalPET/vis/setColor white

/gate/cylindricalPET/daughters/name rsector
/gate/cylindricalPET/daughters/insert box
/gate/rsector/placement/setTranslation 0.0 420.0 0.0 mm
/gate/rsector/geometry/setXLength 64.6 mm
/gate/rsector/geometry/setYLength 20.0 mm
/gate/rsector/geometry/setZLength 263.2 mm
/gate/rsector/setMaterial Vacuum
/gate/rsector/vis/forceWireframe 1
/gate/rsector/vis/forceSolid 0
/gate/rsector/vis/setColor blue

/gate/rsector/daughters/name module
/gate/rsector/daughters/insert box
/gate/module/geometry/setXLength 64.6 mm
/gate/module/geometry/setYLength 20.0 mm
/gate/module/geometry/setZLength 32.2 mm
/gate/module/setMaterial Vacuum
/gate/module/vis/forceWireframe 1
/gate/module/vis/forceSolid 0
/gate/module/vis/setColor yellow

/gate/module/daughters/name submodule
/gate/module/daughters/insert box
/gate/submodule/geometry/setXLength 16.0 mm
/gate/submodule/geometry/setYLength 20.0 mm
/gate/submodule/geometry/setZLength 16.0 mm
/gate/submodule/setMaterial Vacuum
/gate/submodule/vis/forceWireframe 1
/gate/submodule/vis/forceSolid 0
/gate/submodule/vis/setColor red

/gate/submodule/daughters/name crystal
/gate/submodule/daughters/insert box
/gate/crystal/placement/setTranslation 0.0 0.0 0.0 mm
/gate/crystal/geometry/setXLength 3.2 mm
/gate/crystal/geometry/setYLength 20.0 mm
/gate/crystal/geometry/setZLength 3.2 mm
/gate/crystal/setMaterial Vacuum
/gate/crystal/vis/forceWireframe 0
/gate/crystal/vis/forceSolid 1
/gate/crystal/vis/setColor white

/gate/crystal/daughters/name layer0
/gate/crystal/daughters/insert box
/gate/layer0/placement/setTranslation 0.0 0.0 0.0 mm
/gate/layer0/geometry/setXLength 3.2 mm
/gate/layer0/geometry/setYLength 20.0 mm
/gate/layer0/geometry/setZLength 3.2 mm
/gate/layer0/setMaterial LSO
/gate/layer0/vis/forceWireframe 0
/gate/layer0/vis/forceSolid 1
/gate/layer0/vis/setColor cyan

/gate/crystal/repeaters/insert cubicArray
/gate/crystal/cubicArray/setRepeatNumberX 5
/gate/crystal/cubicArray/setRepeatNumberY 1
/gate/crystal/cubicArray/setRepeatNumberZ 5
/gate/crystal/cubicArray/setRepeatVector 3.2 0. 3.2 mm

/gate/submodule/repeaters/insert cubicArray
/gate/submodule/cubicArray/setRepeatNumberX 4
/gate/submodule/cubicArray/setRepeatNumberY 1
/gate/submodule/cubicArray/setRepeatNumberZ 2
/gate/submodule/cubicArray/setRepeatVector 16.2 0. 16.2 mm

/gate/module/repeaters/insert cubicArray
/gate/module/cubicArray/setRepeatNumberX 1
/gate/module/cubicArray/setRepeatNumberY 1
/gate/module/cubicArray/setRepeatNumberZ 8
/gate/module/cubicArray/setRepeatVector 0. 0. 33.0 mm

/gate/rsector/repeaters/insert cubicArray
/gate/rsector/cubicArray/setRepeatNumberX 1
/gate/rsector/cubicArray/setRepeatNumberY 1
/gate/rsector/cubicArray/setRepeatNumberZ 4
/gate/rsector/cubicArray/setRepeatVector 0. 0. 265.6 mm
/gate/rsector/repeaters/insert ring
/gate/rsector/ring/setRepeatNumber 38
/gate/rsector/ring/enableAutoRotation

/gate/systems/cylindricalPET/rsector/attach rsector
/gate/systems/cylindricalPET/module/attach module
/gate/systems/cylindricalPET/submodule/attach submodule
/gate/systems/cylindricalPET/layer0/attach layer0
/gate/systems/cylindricalPET/crystal/attach crystal

/gate/layer0/attachCrystalSD

/gate/world/daughters/name NEMA_IQ
/gate/world/daughters/insert box
/gate/NEMA_IQ/placement/setTranslation 0.0 0.0 0.0 cm
/gate/NEMA_IQ/geometry/setXLength 30. cm
/gate/NEMA_IQ/geometry/setYLength 23. cm
/gate/NEMA_IQ/geometry/setZLength 22. cm
/gate/NEMA_IQ/setMaterial Air
/gate/NEMA_IQ/vis/forceWireframe
/gate/NEMA_IQ/vis/setColor gray

/gate/world/daughters/name NEMA_IQ_cold
/gate/world/daughters/insert box
/gate/NEMA_IQ_cold/placement/setTranslation 0.0 -15. 0.0 cm
/gate/NEMA_IQ_cold/geometry/setXLength 30. cm
/gate/NEMA_IQ_cold/geometry/setYLength 7. cm
/gate/NEMA_IQ_cold/geometry/setZLength 22. cm
/gate/NEMA_IQ_cold/setMaterial Air
/gate/NEMA_IQ_cold/vis/forceWireframe
/gate/NEMA_IQ_cold/vis/setColor gray

/gate/NEMA_IQ/daughters/name outershell1
/gate/NEMA_IQ/daughters/insert cylinder
/gate/outershell1/placement/setTranslation 0.0 -3.5 0.0 cm
/gate/outershell1/geometry/setRmax 15. cm
/gate/outershell1/geometry/setHeight 21.4 cm
/gate/outershell1/geometry/setPhiStart 0. deg
/gate/outershell1/geometry/setDeltaPhi 180. deg
/gate/outershell1/setMaterial Plastic
/gate/outershell1/vis/forceWireframe
/gate/outershell1/vis/setColor red

/gate/outershell1/daughters/name upperinterior
/gate/outershell1/daughters/insert cylinder
/gate/upperinterior/placement/setTranslation 0.0 0.0 0.0 cm
/gate/upperinterior/geometry/setRmax 14.7 cm
/gate/upperinterior/geometry/setRmin  0.0 cm
/gate/upperinterior/geometry/setHeight 21.4 cm
/gate/upperinterior/geometry/setPhiStart 0. deg
/gate/upperinterior/geometry/setDeltaPhi 180. deg
/gate/upperinterior/setMaterial Water
/gate/upperinterior/vis/forceWireframe
/gate/upperinterior/vis/setColor blue

/gate/upperinterior/daughters/name centercyl
/gate/upperinterior/daughters/insert cylinder
/gate/centercyl/placement/setTranslation 0.0 3.5 0.0 cm
/gate/centercyl/geometry/setRmax 2.5 cm
/gate/centercyl/geometry/setHeight 21.4 cm
/gate/centercyl/setMaterial Plastic
/gate/centercyl/vis/forceWireframe
/gate/centercyl/vis/setColor red

/gate/centercyl/daughters/name centercylin
/gate/centercyl/daughters/insert cylinder
/gate/centercylin/placement/setTranslation 0.0 0.0 0.0 cm
/gate/centercylin/geometry/setRmax 2.1 cm
/gate/centercylin/geometry/setRmin 0.0 cm
/gate/centercylin/geometry/setHeight 21.4 cm
/gate/centercylin/setMaterial Water
/gate/centercylin/vis/setColor gray

/gate/upperinterior/daughters/name sphere10
/gate/upperinterior/daughters/insert sphere
/gate/sphere10/placement/setTranslation 2.86 8.45367 3.7 cm
/gate/sphere10/geometry/setRmax 0.6 cm
/gate/sphere10/setMaterial Plastic
/gate/sphere10/vis/forceWireframe
/gate/sphere10/vis/setColor red

/gate/sphere10/daughters/name sphere10in
/gate/sphere10/daughters/insert sphere
/gate/sphere10in/placement/setTranslation 0.0 0.0 0.0 cm
/gate/sphere10in/geometry/setRmax 0.5 cm
/gate/sphere10in/geometry/setRmin 0.0 cm
/gate/sphere10in/setMaterial Water
/gate/sphere10in/vis/setColor gray

/gate/upperinterior/daughters/name fill10
/gate/upperinterior/daughters/insert cylinder
/gate/fill10/placement/setTranslation 2.86 8.45367 7.5 cm
/gate/fill10/geometry/setRmax 0.35 cm
/gate/fill10/geometry/setHeight 6.4 cm
/gate/fill10/setMaterial Plastic
/gate/fill10/vis/forceWireframe
/gate/fill10/vis/setColor red

/gate/fill10/daughters/name fill10in
/gate/fill10/daughters/insert cylinder
/gate/fill10in/placement/setTranslation 0.0 0.0 0.0 cm
/gate/fill10in/geometry/setRmax 0.25 cm
/gate/fill10in/geometry/setRmin 0. cm
/gate/fill10in/geometry/setHeight 6.4 cm
/gate/fill10in/setMaterial Water
/gate/fill10in/vis/setColor gray

/gate/upperinterior/daughters/name sphere13
/gate/upperinterior/daughters/insert sphere
/gate/sphere13/placement/setTranslation -2.86 8.45367 3.7 cm
/gate/sphere13/geometry/setRmax 0.75 cm
/gate/sphere13/setMaterial Plastic
/gate/sphere13/vis/forceWireframe
/gate/sphere13/vis/setColor red

/gate/sphere13/daughters/name sphere13in
/gate/sphere13/daughters/insert sphere
/gate/sphere13in/placement/setTranslation 0.0 0.0 0.0 cm
/gate/sphere13in/geometry/setRmax 0.65 cm
/gate/sphere13in/geometry/setRmin 0.0 cm
/gate/sphere13in/setMaterial Water
/gate/sphere13in/vis/setColor gray

/gate/upperinterior/daughters/name fill13
/gate/upperinterior/daughters/insert cylinder
/gate/fill13/placement/setTranslation -2.86 8.45367 7.5875 cm
/gate/fill13/geometry/setRmax 0.35 cm
/gate/fill13/geometry/setHeight 6.225 cm
/gate/fill13/setMaterial Plastic
/gate/fill13/vis/forceWireframe
/gate/fill13/vis/setColor red

/gate/fill13/daughters/name fill13in
/gate/fill13/daughters/insert cylinder
/gate/fill13in/placement/setTranslation 0.0 0.0 0.0 cm
/gate/fill13in/geometry/setRmax 0.25 cm
/gate/fill13in/geometry/setRmin 0. cm
/gate/fill13in/geometry/setHeight 6.225 cm
/gate/fill13in/setMaterial Water
/gate/fill13in/vis/setColor gray

/gate/upperinterior/daughters/name sphere17
/gate/upperinterior/daughters/insert sphere
/gate/sphere17/placement/setTranslation -5.72 3.5 3.7 cm
/gate/sphere17/geometry/setRmax 0.9 cm
/gate/sphere17/setMaterial Plastic
/gate/sphere17/vis/forceWireframe
/gate/sphere17/vis/setColor red

/gate/sphere17/daughters/name sphere17in
/gate/sphere17/daughters/insert sphere
/gate/sphere17in/placement/setTranslation 0.0 0.0 0.0 cm
/gate/sphere17in/geometry/setRmax 0.85 cm
/gate/sphere17in/geometry/setRmin 0.0 cm
/gate/sphere17in/setMaterial Air
/gate/sphere17in/vis/setColor gray

/gate/upperinterior/daughters/name fill17
/gate/upperinterior/daughters/insert cylinder
/gate/fill17/placement/setTranslation -5.72 3.5 7.675 cm
/gate/fill17/geometry/setRmax 0.35 cm
/gate/fill17/geometry/setHeight 6.05 cm
/gate/fill17/setMaterial Plastic
/gate/fill17/vis/forceWireframe
/gate/fill17/vis/setColor red

/gate/fill17/daughters/name fill17in
/gate/fill17/daughters/insert cylinder
/gate/fill17in/placement/setTranslation 0.0 0.0 0.0 cm
/gate/fill17in/geometry/setRmax 0.25 cm
/gate/fill17in/geometry/setRmin 0. cm
/gate/fill17in/geometry/setHeight 6.05 cm
/gate/fill17in/setMaterial Air
/gate/fill17in/vis/setColor gray

/gate/upperinterior/daughters/name sphere37
/gate/upperinterior/daughters/insert sphere
/gate/sphere37/placement/setTranslation 5.72 3.5 3.7 cm
/gate/sphere37/geometry/setRmax 1.95 cm
/gate/sphere37/setMaterial Plastic
/gate/sphere37/vis/forceWireframe
/gate/sphere37/vis/setColor red

/gate/sphere37/daughters/name sphere37in
/gate/sphere37/daughters/insert sphere
/gate/sphere37in/placement/setTranslation 0.0 0.0 0.0 cm
/gate/sphere37in/geometry/setRmax 1.85 cm
/gate/sphere37in/geometry/setRmin 0.0 cm
/gate/sphere37in/setMaterial Air
/gate/sphere37in/vis/setColor gray

/gate/upperinterior/daughters/name fill37
/gate/upperinterior/daughters/insert cylinder
/gate/fill37/placement/setTranslation 5.72 3.5 8.175 cm
/gate/fill37/geometry/setRmax 0.35 cm
/gate/fill37/geometry/setHeight 5.05 cm
/gate/fill37/setMaterial Plastic
/gate/fill37/vis/forceWireframe
/gate/fill37/vis/setColor red

/gate/fill37/daughters/name fill37in
/gate/fill37/daughters/insert cylinder
/gate/fill37in/placement/setTranslation 0.0 0.0 0.0 cm
/gate/fill37in/geometry/setRmax 0.25 cm
/gate/fill37in/geometry/setRmin 0. cm
/gate/fill37in/geometry/setHeight 5.05 cm
/gate/fill37in/setMaterial Air
/gate/fill37in/vis/setColor gray

/gate/NEMA_IQ/daughters/name topshell1
/gate/NEMA_IQ/daughters/insert cylinder
/gate/topshell1/placement/setTranslation 0.0 -3.5 10.85 cm
/gate/topshell1/geometry/setRmax 15. cm
/gate/topshell1/geometry/setRmin 0. cm
/gate/topshell1/geometry/setHeight 0.3 cm
/gate/topshell1/geometry/setPhiStart 0. deg
/gate/topshell1/geometry/setDeltaPhi 180. deg
/gate/topshell1/setMaterial Plastic
/gate/topshell1/vis/forceWireframe
/gate/topshell1/vis/setColor yellow

/gate/NEMA_IQ/daughters/name bottomshell1
/gate/NEMA_IQ/daughters/insert cylinder
/gate/bottomshell1/placement/setTranslation 0.0 -3.5 -10.85 cm
/gate/bottomshell1/geometry/setRmax 15. cm
/gate/bottomshell1/geometry/setRmin 0. cm
/gate/bottomshell1/geometry/setHeight 0.3 cm
/gate/bottomshell1/geometry/setPhiStart 0. deg
/gate/bottomshell1/geometry/setDeltaPhi 180. deg
/gate/bottomshell1/setMaterial Plastic
/gate/bottomshell1/vis/setColor yellow

/gate/NEMA_IQ/daughters/name outershell2
/gate/NEMA_IQ/daughters/insert cylinder
/gate/outershell2/placement/setTranslation 7.0 -3.5 0.0 cm
/gate/outershell2/geometry/setRmax 8. cm
/gate/outershell2/geometry/setHeight 21.4 cm
/gate/outershell2/geometry/setPhiStart 270. deg
/gate/outershell2/geometry/setDeltaPhi  90. deg
/gate/outershell2/setMaterial Plastic
/gate/outershell2/vis/forceWireframe
/gate/outershell2/vis/setColor red

/gate/outershell2/daughters/name LLinterior
/gate/outershell2/daughters/insert cylinder
/gate/LLinterior/placement/setTranslation 0.0 0.0 0.0 cm
/gate/LLinterior/geometry/setRmax 7.7 cm
/gate/LLinterior/geometry/setRmin 0. cm
/gate/LLinterior/geometry/setHeight 21.4 cm
/gate/LLinterior/geometry/setPhiStart 270. deg
/gate/LLinterior/geometry/setDeltaPhi  90. deg
/gate/LLinterior/setMaterial Water
/gate/LLinterior/vis/forceWireframe
/gate/LLinterior/vis/setColor blue

/gate/NEMA_IQ/daughters/name outershell3
/gate/NEMA_IQ/daughters/insert cylinder
/gate/outershell3/placement/setTranslation -7.0 -3.5 0.0 cm
/gate/outershell3/geometry/setRmax 8. cm
/gate/outershell3/geometry/setHeight 21.4 cm
/gate/outershell3/geometry/setPhiStart 180. deg
/gate/outershell3/geometry/setDeltaPhi  90. deg
/gate/outershell3/setMaterial Plastic
/gate/outershell3/vis/forceWireframe
/gate/outershell3/vis/setColor red

/gate/outershell3/daughters/name LRinterior
/gate/outershell3/daughters/insert cylinder
/gate/LRinterior/placement/setTranslation 0.0 0.0 0.0 cm
/gate/LRinterior/geometry/setRmax 7.7 cm
/gate/LRinterior/geometry/setRmin 0. cm
/gate/LRinterior/geometry/setHeight 21.4 cm
/gate/LRinterior/geometry/setPhiStart 180. deg
/gate/LRinterior/geometry/setDeltaPhi  90. deg
/gate/LRinterior/setMaterial Water
/gate/LRinterior/vis/forceWireframe
/gate/LRinterior/vis/setColor blue

/gate/NEMA_IQ/daughters/name outershell4
/gate/NEMA_IQ/daughters/insert box
/gate/outershell4/placement/setTranslation 0.0 -7.5 0.0 cm
/gate/outershell4/geometry/setXLength 14. cm
/gate/outershell4/geometry/setYLength  8. cm
/gate/outershell4/geometry/setZLength 21.4 cm
/gate/outershell4/setMaterial Plastic
/gate/outershell4/vis/forceWireframe
/gate/outershell4/vis/setColor red

/gate/outershell4/daughters/name boxinterior
/gate/outershell4/daughters/insert box
/gate/boxinterior/placement/setTranslation 0.0 0.15 0.0 cm
/gate/boxinterior/geometry/setXLength 14. cm
/gate/boxinterior/geometry/setYLength  7.7 cm
/gate/boxinterior/geometry/setZLength 21.4 cm
/gate/boxinterior/setMaterial Water
/gate/boxinterior/vis/forceWireframe
/gate/boxinterior/vis/setColor blue

/gate/boxinterior/daughters/name sphere22
/gate/boxinterior/daughters/insert sphere
/gate/sphere22/placement/setTranslation -2.86 2.39633 3.7 cm
/gate/sphere22/geometry/setRmax 1.2 cm
/gate/sphere22/setMaterial Plastic
/gate/sphere22/vis/forceWireframe
/gate/sphere22/vis/setColor red

/gate/sphere22/daughters/name sphere22in
/gate/sphere22/daughters/insert sphere
/gate/sphere22in/placement/setTranslation 0.0 0.0 0.0 cm
/gate/sphere22in/geometry/setRmax 1.1 cm
/gate/sphere22in/geometry/setRmin 0.0 cm
/gate/sphere22in/setMaterial Water
/gate/sphere22in/vis/setColor gray

/gate/boxinterior/daughters/name fill22
/gate/boxinterior/daughters/insert cylinder
/gate/fill22/placement/setTranslation -2.86 2.39633 7.8 cm
/gate/fill22/geometry/setRmax 0.35 cm
/gate/fill22/geometry/setHeight 5.8 cm
/gate/fill22/setMaterial Plastic
/gate/fill22/vis/forceWireframe
/gate/fill22/vis/setColor red

/gate/fill22/daughters/name fill22in
/gate/fill22/daughters/insert cylinder
/gate/fill22in/placement/setTranslation 0.0 0.0 0.0 cm
/gate/fill22in/geometry/setRmax 0.25 cm
/gate/fill22in/geometry/setRmin 0. cm
/gate/fill22in/geometry/setHeight 5.8 cm
/gate/fill22in/setMaterial Water
/gate/fill22in/vis/setColor gray

/gate/boxinterior/daughters/name sphere28
/gate/boxinterior/daughters/insert sphere
/gate/sphere28/placement/setTranslation 2.86 2.39633 3.7 cm
/gate/sphere28/geometry/setRmax 1.5 cm
/gate/sphere28/setMaterial Plastic
/gate/sphere28/vis/forceWireframe
/gate/sphere28/vis/setColor red

/gate/sphere28/daughters/name sphere28in
/gate/sphere28/daughters/insert sphere
/gate/sphere28in/placement/setTranslation 0.0 0.0 0.0 cm
/gate/sphere28in/geometry/setRmax 1.4 cm
/gate/sphere28in/geometry/setRmin 0.0 cm
/gate/sphere28in/setMaterial Water
/gate/sphere28in/vis/setColor gray

/gate/boxinterior/daughters/name fill28
/gate/boxinterior/daughters/insert cylinder
/gate/fill28/placement/setTranslation 2.86 2.39633 7.95 cm
/gate/fill28/geometry/setRmax 0.35 cm
/gate/fill28/geometry/setHeight 5.5 cm
/gate/fill28/setMaterial Plastic
/gate/fill28/vis/forceWireframe
/gate/fill28/vis/setColor red

/gate/fill28/daughters/name fill28in
/gate/fill28/daughters/insert cylinder
/gate/fill28in/placement/setTranslation 0.0 0.0 0.0 cm
/gate/fill28in/geometry/setRmax 0.25 cm
/gate/fill28in/geometry/setRmin 0. cm
/gate/fill28in/geometry/setHeight 5.5 cm
/gate/fill28in/setMaterial Water
/gate/fill28in/vis/setColor gray

/gate/NEMA_IQ/daughters/name topshell2
/gate/NEMA_IQ/daughters/insert cylinder
/gate/topshell2/placement/setTranslation 7.0 -3.5 10.85 cm
/gate/topshell2/geometry/setRmax 8. cm
/gate/topshell2/geometry/setRmin 0. cm
/gate/topshell2/geometry/setHeight 0.3 cm
/gate/topshell2/geometry/setPhiStart 270. deg
/gate/topshell2/geometry/setDeltaPhi  90. deg
/gate/topshell2/setMaterial Plastic
/gate/topshell2/vis/setColor yellow

/gate/NEMA_IQ/daughters/name topshell3
/gate/NEMA_IQ/daughters/insert cylinder
/gate/topshell3/placement/setTranslation -7.0 -3.5 10.85 cm
/gate/topshell3/geometry/setRmax 8. cm
/gate/topshell3/geometry/setRmin 0. cm
/gate/topshell3/geometry/setHeight 0.3 cm
/gate/topshell3/geometry/setPhiStart 180. deg
/gate/topshell3/geometry/setDeltaPhi  90. deg
/gate/topshell3/setMaterial Plastic
/gate/topshell3/vis/setColor yellow

/gate/NEMA_IQ/daughters/name topshell4
/gate/NEMA_IQ/daughters/insert box
/gate/topshell4/placement/setTranslation 0.0 -7.5 10.85 cm
/gate/topshell4/geometry/setXLength 14. cm
/gate/topshell4/geometry/setYLength 8. cm
/gate/topshell4/geometry/setZLength 0.3 cm
/gate/topshell4/setMaterial Plastic
/gate/topshell4/vis/forceWireframe
/gate/topshell4/vis/setColor yellow

/gate/NEMA_IQ/daughters/name bottomshell2
/gate/NEMA_IQ/daughters/insert cylinder
/gate/bottomshell2/placement/setTranslation 7.0 -3.5 -10.85 cm
/gate/bottomshell2/geometry/setRmax 8. cm
/gate/bottomshell2/geometry/setRmin 0. cm
/gate/bottomshell2/geometry/setHeight 0.3 cm
/gate/bottomshell2/geometry/setPhiStart 270. deg
/gate/bottomshell2/geometry/setDeltaPhi  90. deg
/gate/bottomshell2/setMaterial Plastic
/gate/bottomshell2/vis/setColor yellow

/gate/NEMA_IQ/daughters/name bottomshell3
/gate/NEMA_IQ/daughters/insert cylinder
/gate/bottomshell3/placement/setTranslation -7.0 -3.5 -10.85 cm
/gate/bottomshell3/geometry/setRmax 8. cm
/gate/bottomshell3/geometry/setRmin 0. cm
/gate/bottomshell3/geometry/setHeight 0.3 cm
/gate/bottomshell3/geometry/setPhiStart 180. deg
/gate/bottomshell3/geometry/setDeltaPhi  90. deg
/gate/bottomshell3/setMaterial Plastic
/gate/bottomshell3/vis/setColor yellow

/gate/NEMA_IQ/daughters/name bottomshell4
/gate/NEMA_IQ/daughters/insert box
/gate/bottomshell4/placement/setTranslation 0.0 -7.5 -10.85 cm
/gate/bottomshell4/geometry/setXLength 14. cm
/gate/bottomshell4/geometry/setYLength 8. cm
/gate/bottomshell4/geometry/setZLength 0.3 cm
/gate/bottomshell4/setMaterial Plastic
/gate/bottomshell4/vis/setColor yellow

/gate/NEMA_IQ/attachPhantomSD
/gate/NEMA_IQ_cold/attachPhantomSD
/gate/outershell1/attachPhantomSD
/gate/upperinterior/attachPhantomSD
/gate/centercyl/attachPhantomSD
/gate/centercylin/attachPhantomSD
/gate/sphere10/attachPhantomSD
/gate/sphere10in/attachPhantomSD
/gate/fill10/attachPhantomSD
/gate/fill10in/attachPhantomSD
/gate/sphere13/attachPhantomSD
/gate/sphere13in/attachPhantomSD
/gate/fill13/attachPhantomSD
/gate/fill13in/attachPhantomSD
/gate/sphere17/attachPhantomSD
/gate/sphere17in/attachPhantomSD
/gate/fill17/attachPhantomSD
/gate/fill17in/attachPhantomSD
/gate/sphere37/attachPhantomSD
/gate/sphere37in/attachPhantomSD
/gate/fill37/attachPhantomSD
/gate/fill37in/attachPhantomSD
/gate/topshell1/attachPhantomSD
/gate/bottomshell1/attachPhantomSD
/gate/outershell2/attachPhantomSD
/gate/LLinterior/attachPhantomSD
/gate/outershell3/attachPhantomSD
/gate/LRinterior/attachPhantomSD
/gate/outershell4/attachPhantomSD
/gate/boxinterior/attachPhantomSD
/gate/sphere22/attachPhantomSD
/gate/sphere22in/attachPhantomSD
/gate/fill22/attachPhantomSD
/gate/fill22in/attachPhantomSD
/gate/sphere28/attachPhantomSD
/gate/sphere28in/attachPhantomSD
/gate/fill28/attachPhantomSD
/gate/fill28in/attachPhantomSD
/gate/topshell2/attachPhantomSD
/gate/topshell3/attachPhantomSD
/gate/topshell4/attachPhantomSD
/gate/bottomshell2/attachPhantomSD
/gate/bottomshell3/attachPhantomSD
/gate/bottomshell4/attachPhantomSD

/gate/physics/addProcess PhotoElectric gamma
/gate/physics/processes/PhotoElectric/setModel LivermoreModel

/gate/physics/addProcess Compton gamma
/gate/physics/processes/Compton/setModel LivermorePolarizedModel

/gate/physics/processList Enabled
/gate/physics/processList Initialized

/gate/physics/Gamma/SetCutInRegion world 10 mm
/gate/physics/Electron/SetCutInRegion world 10 mm
/gate/physics/Positron/SetCutInRegion world 10 mm

/gate/physics/displayCuts

/gate/run/initialize

/gate/physics/displayCuts

/vis/disable

/gate/source/addSource                        upperinterior_hot_background PositroniumSource
/gate/source/upperinterior_hot_background/gps/pos/centre     0.0 -3.5 0.0 cm
/gate/source/upperinterior_hot_background/gps/pos/type       Volume
/gate/source/upperinterior_hot_background/gps/pos/shape      Cylinder
/gate/source/upperinterior_hot_background/gps/pos/radius     14.7 cm
/gate/source/upperinterior_hot_background/gps/pos/halfz      10.7 cm
/gate/source/upperinterior_hot_background/setActivity 7896686.4 Bq
/gate/source/upperinterior_hot_background/setType Ps
/gate/source/upperinterior_hot_background/setPositroniumFractions 0.14 0.62833 0.00167 0.22721 0.00279
/gate/source/upperinterior_hot_background/setPositroniumLifetimes 0.14 0.4 0.4 1.8 1.8 ns
/gate/source/upperinterior_hot_background/setDecayKinds k2Gamma k2Gamma k3Gamma k2Gamma k3Gamma
/gate/source/upperinterior_hot_background/setPositronInteractions kParaPs kDirect kDirect kOrthoPs kOrthoPs
/gate/source/upperinterior_hot_background/setPromptPhotonProbabilites 1 1 1 1 1
/gate/source/upperinterior_hot_background/setPromptPhotonEnergies 1.274 1.274 1.274 1.274 1.274 MeV
/gate/source/upperinterior_hot_background/gps/particle   gamma
/gate/source/upperinterior_hot_background/gps/Forbid     NEMA_IQ
/gate/source/upperinterior_hot_background/gps/Forbid     NEMA_IQ_cold
/gate/source/upperinterior_hot_background/gps/Forbid     centercyl
/gate/source/upperinterior_hot_background/gps/Forbid     centercylin
/gate/source/upperinterior_hot_background/gps/Forbid     sphere10
/gate/source/upperinterior_hot_background/gps/Forbid     sphere10in
/gate/source/upperinterior_hot_background/gps/Forbid     fill10
/gate/source/upperinterior_hot_background/gps/Forbid     fill10in
/gate/source/upperinterior_hot_background/gps/Forbid     sphere13
/gate/source/upperinterior_hot_background/gps/Forbid     sphere13in
/gate/source/upperinterior_hot_background/gps/Forbid     fill13
/gate/source/upperinterior_hot_background/gps/Forbid     fill13in
/gate/source/upperinterior_hot_background/gps/Forbid     sphere17
/gate/source/upperinterior_hot_background/gps/Forbid     sphere17in
/gate/source/upperinterior_hot_background/gps/Forbid     fill17
/gate/source/upperinterior_hot_background/gps/Forbid     fill17in
/gate/source/upperinterior_hot_background/gps/Forbid     sphere37
/gate/source/upperinterior_hot_background/gps/Forbid     sphere37in
/gate/source/upperinterior_hot_background/gps/Forbid     fill37
/gate/source/upperinterior_hot_background/gps/Forbid     fill37in
/gate/source/upperinterior_hot_background/gps/Forbid     sphere22
/gate/source/upperinterior_hot_background/gps/Forbid     sphere22in
/gate/source/upperinterior_hot_background/gps/Forbid     fill22
/gate/source/upperinterior_hot_background/gps/Forbid     fill22in
/gate/source/upperinterior_hot_background/gps/Forbid     sphere28
/gate/source/upperinterior_hot_background/gps/Forbid     sphere28in
/gate/source/upperinterior_hot_background/gps/Forbid     fill28
/gate/source/upperinterior_hot_background/gps/Forbid     fill28in
/gate/source/upperinterior_hot_background/gps/Forbid     boxinterior
/gate/source/upperinterior_hot_background/gps/Forbid     LLinterior
/gate/source/upperinterior_hot_background/gps/Forbid     LRinterior
/gate/source/upperinterior_hot_background/gps/Forbid     outershell1
/gate/source/upperinterior_hot_background/gps/Forbid     outershell2
/gate/source/upperinterior_hot_background/gps/Forbid     outershell3
/gate/source/upperinterior_hot_background/gps/Forbid     outershell4
/gate/source/upperinterior_hot_background/dump           35

/gate/source/addSource                        LRinterior_hot_background PositroniumSource
/gate/source/LRinterior_hot_background/gps/pos/centre        -7.0 -3.5 0.0 cm
/gate/source/LRinterior_hot_background/gps/pos/type          Volume
/gate/source/LRinterior_hot_background/gps/pos/shape         Cylinder
/gate/source/LRinterior_hot_background/gps/pos/radius        7.7 cm
/gate/source/LRinterior_hot_background/gps/pos/halfz         10.7 cm
/gate/source/LRinterior_hot_background/setActivity    1089650.4 Bq
/gate/source/LRinterior_hot_background/setType Ps
/gate/source/LRinterior_hot_background/setPositroniumFractions 0.14 0.62833 0.00167 0.22721 0.00279
/gate/source/LRinterior_hot_background/setPositroniumLifetimes 0.14 0.4 0.4 1.8 1.8 ns
/gate/source/LRinterior_hot_background/setDecayKinds k2Gamma k2Gamma k3Gamma k2Gamma k3Gamma
/gate/source/LRinterior_hot_background/setPositronInteractions kParaPs kDirect kDirect kOrthoPs kOrthoPs
/gate/source/LRinterior_hot_background/setPromptPhotonProbabilites 1 1 1 1 1
/gate/source/LRinterior_hot_background/setPromptPhotonEnergies 1.274 1.274 1.274 1.274 1.274 MeV
/gate/source/LRinterior_hot_background/gps/particle      gamma
/gate/source/LRinterior_hot_background/gps/Forbid        upperinterior
/gate/source/LRinterior_hot_background/gps/Forbid        boxinterior
/gate/source/LRinterior_hot_background/gps/Forbid        centercyl
/gate/source/LRinterior_hot_background/gps/Forbid        centercylin
/gate/source/LRinterior_hot_background/gps/Forbid        sphere17
/gate/source/LRinterior_hot_background/gps/Forbid        sphere17in
/gate/source/LRinterior_hot_background/gps/Forbid        fill17
/gate/source/LRinterior_hot_background/gps/Forbid        fill17in
/gate/source/LRinterior_hot_background/gps/Forbid        sphere22
/gate/source/LRinterior_hot_background/gps/Forbid        sphere22in
/gate/source/LRinterior_hot_background/gps/Forbid        fill22
/gate/source/LRinterior_hot_background/gps/Forbid        fill22in
/gate/source/LRinterior_hot_background/dump              12

/gate/source/addSource                        LLinterior_hot_background PositroniumSource
/gate/source/LLinterior_hot_background/gps/pos/centre        7.0 -3.5 0.0 cm
/gate/source/LLinterior_hot_background/gps/pos/type          Volume
/gate/source/LLinterior_hot_background/gps/pos/shape         Cylinder
/gate/source/LLinterior_hot_background/gps/pos/radius        7.7 cm
/gate/source/LLinterior_hot_background/gps/pos/halfz         10.7 cm
/gate/source/LLinterior_hot_background/setActivity    1089650.4 Bq
/gate/source/LLinterior_hot_background/setType Ps
/gate/source/LLinterior_hot_background/setPositroniumFractions 0.14 0.62833 0.00167 0.22721 0.00279
/gate/source/LLinterior_hot_background/setPositroniumLifetimes 0.14 0.4 0.4 1.8 1.8 ns
/gate/source/LLinterior_hot_background/setDecayKinds k2Gamma k2Gamma k3Gamma k2Gamma k3Gamma
/gate/source/LLinterior_hot_background/setPositronInteractions kParaPs kDirect kDirect kOrthoPs kOrthoPs
/gate/source/LLinterior_hot_background/setPromptPhotonProbabilites 1 1 1 1 1
/gate/source/LLinterior_hot_background/setPromptPhotonEnergies 1.274 1.274 1.274 1.274 1.274 MeV
/gate/source/LLinterior_hot_background/gps/particle      gamma
/gate/source/LLinterior_hot_background/gps/Forbid        upperinterior
/gate/source/LLinterior_hot_background/gps/Forbid        boxinterior
/gate/source/LLinterior_hot_background/gps/Forbid        centercyl
/gate/source/LLinterior_hot_background/gps/Forbid        centercylin
/gate/source/LLinterior_hot_background/gps/Forbid        sphere28
/gate/source/LLinterior_hot_background/gps/Forbid        sphere28in
/gate/source/LLinterior_hot_background/gps/Forbid        fill28
/gate/source/LLinterior_hot_background/gps/Forbid        fill28in
/gate/source/LLinterior_hot_background/gps/Forbid        sphere37
/gate/source/LLinterior_hot_background/gps/Forbid        sphere37in
/gate/source/LLinterior_hot_background/gps/Forbid        fill37
/gate/source/LLinterior_hot_background/gps/Forbid        fill37in
/gate/source/LLinterior_hot_background/dump              12

/gate/source/addSource                        interiorbox_hot_background PositroniumSource
/gate/source/interiorbox_hot_background/gps/pos/centre       0.0 -7.35 0.0 cm
/gate/source/interiorbox_hot_background/gps/pos/type         Volume
/gate/source/interiorbox_hot_background/gps/pos/shape        Para
/gate/source/interiorbox_hot_background/gps/pos/halfx        7. cm
/gate/source/interiorbox_hot_background/gps/pos/halfy        3.85 cm
/gate/source/interiorbox_hot_background/gps/pos/halfz        10.7 cm
/gate/source/interiorbox_hot_background/setActivity    2497445.5 Bq
/gate/source/interiorbox_hot_background/setType Ps
/gate/source/interiorbox_hot_background/setPositroniumFractions 0.14 0.62833 0.00167 0.22721 0.00279
/gate/source/interiorbox_hot_background/setPositroniumLifetimes 0.14 0.4 0.4 1.8 1.8 ns
/gate/source/interiorbox_hot_background/setDecayKinds k2Gamma k2Gamma k3Gamma k2Gamma k3Gamma
/gate/source/interiorbox_hot_background/setPositronInteractions kParaPs kDirect kDirect kOrthoPs kOrthoPs
/gate/source/interiorbox_hot_background/setPromptPhotonProbabilites 1 1 1 1 1
/gate/source/interiorbox_hot_background/setPromptPhotonEnergies 1.274 1.274 1.274 1.274 1.274 MeV
/gate/source/interiorbox_hot_background/gps/particle     gamma
/gate/source/interiorbox_hot_background/gps/Forbid       sphere22
/gate/source/interiorbox_hot_background/gps/Forbid       sphere22in
/gate/source/interiorbox_hot_background/gps/Forbid       fill22
/gate/source/interiorbox_hot_background/gps/Forbid       fill22in
/gate/source/interiorbox_hot_background/gps/Forbid       sphere28
/gate/source/interiorbox_hot_background/gps/Forbid       sphere28in
/gate/source/interiorbox_hot_background/gps/Forbid       fill28
/gate/source/interiorbox_hot_background/gps/Forbid       fill28in
/gate/source/interiorbox_hot_background/dump             8

/gate/source/addSource                        central_cylinder PositroniumSource
/gate/source/central_cylinder/gps/pos/centre        0.0 0.0 0.0 cm
/gate/source/central_cylinder/gps/pos/type          Volume
/gate/source/central_cylinder/gps/pos/shape         Cylinder
/gate/source/central_cylinder/gps/pos/radius        2.1 cm
/gate/source/central_cylinder/gps/pos/halfz         10.7 cm
/gate/source/central_cylinder/setActivity    148242.3 Bq
/gate/source/central_cylinder/setType Ps
/gate/source/central_cylinder/setPositroniumFractions 0.13 0.75796 0.00204 0.04729 0.0258 0.01875 0.00769 0.00071 0.0012 0.00325 0.00531
/gate/source/central_cylinder/setPositroniumLifetimes 0.125 0.4 0.4 2.1 6.3 21 58 2.1 6.3 21 58 ns
/gate/source/central_cylinder/setDecayKinds k2Gamma k2Gamma k3Gamma k2Gamma k2Gamma k2Gamma k2Gamma k3Gamma k3Gamma k3Gamma k3Gamma
/gate/source/central_cylinder/setPositronInteractions kParaPs kDirect kDirect kOrthoPs kOrthoPs kOrthoPs kOrthoPs kOrthoPs kOrthoPs kOrthoPs kOrthoPs
/gate/source/central_cylinder/setPromptPhotonProbabilites 1 1 1 1 1 1 1 1 1 1 1
/gate/source/central_cylinder/setPromptPhotonEnergies 1.274 1.274 1.274 1.274 1.274 1.274 1.274 1.274 1.274 1.274 1.274 MeV
/gate/source/central_cylinder/gps/particle     gamma

/gate/source/addSource                        sphere10mm PositroniumSource
/gate/source/sphere10mm/gps/pos/centre            2.86 4.95367 3.7 cm
/gate/source/sphere10mm/gps/pos/type              Volume
/gate/source/sphere10mm/gps/pos/shape             Sphere
/gate/source/sphere10mm/gps/pos/radius            0.5 cm
/gate/source/sphere10mm/setActivity    3351.0 Bq
/gate/source/sphere10mm/setType Ps
/gate/source/sphere10mm/setPositroniumFractions 0.12 0.69313 0.00187 0.18169 0.00331
/gate/source/sphere10mm/setPositroniumLifetimes 0.152 0.42 0.42 2.54 2.54 ns
/gate/source/sphere10mm/setDecayKinds k2Gamma k2Gamma k3Gamma k2Gamma k3Gamma
/gate/source/sphere10mm/setPositronInteractions kParaPs kDirect kDirect kOrthoPs kOrthoPs
/gate/source/sphere10mm/setPromptPhotonProbabilites 1 1 1 1 1
/gate/source/sphere10mm/setPromptPhotonEnergies 1.274 1.274 1.274 1.274 1.274 MeV
/gate/source/sphere10mm/gps/particle          gamma

/gate/source/addSource                        capillary10mm PositroniumSource
/gate/source/capillary10mm/gps/pos/centre         2.86 4.95367 7.5 cm
/gate/source/capillary10mm/gps/pos/type           Volume
/gate/source/capillary10mm/gps/pos/shape          Cylinder
/gate/source/capillary10mm/gps/pos/radius         0.25 cm
/gate/source/capillary10mm/gps/pos/halfz          3.2 cm
/gate/source/capillary10mm/setActivity    1633.6 Bq
/gate/source/capillary10mm/setType Ps
/gate/source/capillary10mm/setPositroniumFractions 0.12 0.69313 0.00187 0.18169 0.00331
/gate/source/capillary10mm/setPositroniumLifetimes 0.152 0.42 0.42 2.54 2.54 ns
/gate/source/capillary10mm/setDecayKinds k2Gamma k2Gamma k3Gamma k2Gamma k3Gamma
/gate/source/capillary10mm/setPositronInteractions kParaPs kDirect kDirect kOrthoPs kOrthoPs
/gate/source/capillary10mm/setPromptPhotonProbabilites 1 1 1 1 1
/gate/source/capillary10mm/setPromptPhotonEnergies 1.274 1.274 1.274 1.274 1.274 MeV
/gate/source/capillary10mm/gps/particle       gamma

/gate/source/addSource                        sphere13mm             PositroniumSource
/gate/source/sphere13mm/gps/pos/centre            -2.86 4.95367 3.7 cm
/gate/source/sphere13mm/gps/pos/type              Volume
/gate/source/sphere13mm/gps/pos/shape             Sphere
/gate/source/sphere13mm/gps/pos/radius            0.65 cm
/gate/source/sphere13mm/setActivity    7362.2 Bq
/gate/source/sphere13mm/setType Ps
/gate/source/sphere13mm/setPositroniumFractions 0.092 0.76095 0.00205 0.14291 0.00209
/gate/source/sphere13mm/setPositroniumLifetimes 0.15 0.44 0.44 2.04 2.04 ns
/gate/source/sphere13mm/setDecayKinds k2Gamma k2Gamma k3Gamma k2Gamma k3Gamma
/gate/source/sphere13mm/setPositronInteractions kParaPs kDirect kDirect kOrthoPs kOrthoPs
/gate/source/sphere13mm/setPromptPhotonProbabilites 1 1 1 1 1
/gate/source/sphere13mm/setPromptPhotonEnergies 1.274 1.274 1.274 1.274 1.274 MeV
/gate/source/sphere13mm/gps/particle          gamma

/gate/source/addSource                        capillary13mm PositroniumSource
/gate/source/capillary13mm/gps/pos/centre         -2.86 4.95367 7.5875 cm
/gate/source/capillary13mm/gps/pos/type           Volume
/gate/source/capillary13mm/gps/pos/shape          Cylinder
/gate/source/capillary13mm/gps/pos/radius         0.25 cm
/gate/source/capillary13mm/gps/pos/halfz          3.1125 cm
/gate/source/capillary13mm/setActivity    1589.0 Bq
/gate/source/capillary13mm/setType Ps
/gate/source/capillary13mm/setPositroniumFractions 0.092 0.76095 0.00205 0.14291 0.00209
/gate/source/capillary13mm/setPositroniumLifetimes 0.15 0.44 0.44 2.04 2.04 ns
/gate/source/capillary13mm/setDecayKinds k2Gamma k2Gamma k3Gamma k2Gamma k3Gamma
/gate/source/capillary13mm/setPositronInteractions kParaPs kDirect kDirect kOrthoPs kOrthoPs
/gate/source/capillary13mm/setPromptPhotonProbabilites 1 1 1 1 1
/gate/source/capillary13mm/setPromptPhotonEnergies 1.274 1.274 1.274 1.274 1.274 MeV
/gate/source/capillary13mm/gps/particle       gamma

/gate/source/addSource                        capillary17mm PositroniumSource
/gate/source/capillary17mm/gps/pos/centre         -5.72 0. 7.675 cm
/gate/source/capillary17mm/gps/pos/type           Volume
/gate/source/capillary17mm/gps/pos/shape          Cylinder
/gate/source/capillary17mm/gps/pos/radius         0.25 cm
/gate/source/capillary17mm/gps/pos/halfz          3.025 cm
/gate/source/capillary17mm/setActivity    1544.3 Bq
/gate/source/capillary17mm/setType Ps
/gate/source/capillary17mm/setPositroniumFractions 0.092 0.76095 0.00205 0.14291 0.00209
/gate/source/capillary17mm/setPositroniumLifetimes 0.15 0.44 0.44 2.04 2.04 ns
/gate/source/capillary17mm/setDecayKinds k2Gamma k2Gamma k3Gamma k2Gamma k3Gamma
/gate/source/capillary17mm/setPositronInteractions kParaPs kDirect kDirect kOrthoPs kOrthoPs
/gate/source/capillary17mm/setPromptPhotonProbabilites 1 1 1 1 1
/gate/source/capillary17mm/setPromptPhotonEnergies 1.274 1.274 1.274 1.274 1.274 MeV
/gate/source/capillary17mm/gps/particle       gamma

/gate/source/addSource                        sphere22mm PositroniumSource
/gate/source/sphere22mm/gps/pos/centre            -2.86 -4.95367 3.7 cm
/gate/source/sphere22mm/gps/pos/type              Volume
/gate/source/sphere22mm/gps/pos/shape             Sphere
/gate/source/sphere22mm/gps/pos/radius            1.1 cm
/gate/source/sphere22mm/setActivity    35681.8 Bq
/gate/source/sphere22mm/setType Ps
/gate/source/sphere22mm/setPositroniumFractions 0.12 0.69313 0.00187 0.18169 0.00331
/gate/source/sphere22mm/setPositroniumLifetimes 0.152 0.42 0.42 2.54 2.54 ns
/gate/source/sphere22mm/setDecayKinds k2Gamma k2Gamma k3Gamma k2Gamma k3Gamma
/gate/source/sphere22mm/setPositronInteractions kParaPs kDirect kDirect kOrthoPs kOrthoPs
/gate/source/sphere22mm/setPromptPhotonProbabilites 1 1 1 1 1
/gate/source/sphere22mm/setPromptPhotonEnergies 1.274 1.274 1.274 1.274 1.274 MeV
/gate/source/sphere22mm/gps/particle          gamma

/gate/source/addSource                        capillary22mm PositroniumSource
/gate/source/capillary22mm/gps/pos/centre         -2.86 -4.95367 7.8 cm
/gate/source/capillary22mm/gps/pos/type           Volume
/gate/source/capillary22mm/gps/pos/shape          Cylinder
/gate/source/capillary22mm/gps/pos/radius         0.25 cm
/gate/source/capillary22mm/gps/pos/halfz          2.9 cm
/gate/source/capillary22mm/setActivity    1480.5 Bq
/gate/source/capillary22mm/setType Ps
/gate/source/capillary22mm/setPositroniumFractions 0.12 0.69313 0.00187 0.18169 0.00331
/gate/source/capillary22mm/setPositroniumLifetimes 0.152 0.42 0.42 2.54 2.54 ns
/gate/source/capillary22mm/setDecayKinds k2Gamma k2Gamma k3Gamma k2Gamma k3Gamma
/gate/source/capillary22mm/setPositronInteractions kParaPs kDirect kDirect kOrthoPs kOrthoPs
/gate/source/capillary22mm/setPromptPhotonProbabilites 1 1 1 1 1
/gate/source/capillary22mm/setPromptPhotonEnergies 1.274 1.274 1.274 1.274 1.274 MeV
/gate/source/capillary22mm/gps/particle       gamma

/gate/source/addSource                        sphere28mm             PositroniumSource
/gate/source/sphere28mm/gps/pos/centre            2.86 -4.95367 3.7 cm
/gate/source/sphere28mm/gps/pos/type              Volume
/gate/source/sphere28mm/gps/pos/shape             Sphere
/gate/source/sphere28mm/gps/pos/radius            1.4 cm
/gate/source/sphere28mm/setActivity    73561.9 Bq
/gate/source/sphere28mm/setType Ps
/gate/source/sphere28mm/setPositroniumFractions 0.092 0.76095 0.00205 0.14291 0.00209
/gate/source/sphere28mm/setPositroniumLifetimes 0.15 0.44 0.44 2.04 2.04 ns
/gate/source/sphere28mm/setDecayKinds k2Gamma k2Gamma k3Gamma k2Gamma k3Gamma
/gate/source/sphere28mm/setPositronInteractions kParaPs kDirect kDirect kOrthoPs kOrthoPs
/gate/source/sphere28mm/setPromptPhotonProbabilites 1 1 1 1 1
/gate/source/sphere28mm/setPromptPhotonEnergies 1.274 1.274 1.274 1.274 1.274 MeV
/gate/source/sphere28mm/gps/particle          gamma

/gate/source/addSource                        capillary28mm PositroniumSource
/gate/source/capillary28mm/gps/pos/centre         2.86 -4.95367 7.95 cm
/gate/source/capillary28mm/gps/pos/type           Volume
/gate/source/capillary28mm/gps/pos/shape          Cylinder
/gate/source/capillary28mm/gps/pos/radius         0.25 cm
/gate/source/capillary28mm/gps/pos/halfz          2.75 cm
/gate/source/capillary28mm/setActivity    1403.9 Bq
/gate/source/capillary28mm/setType Ps
/gate/source/capillary28mm/setPositroniumFractions 0.092 0.76095 0.00205 0.14291 0.00209
/gate/source/capillary28mm/setPositroniumLifetimes 0.15 0.44 0.44 2.04 2.04 ns
/gate/source/capillary28mm/setDecayKinds k2Gamma k2Gamma k3Gamma k2Gamma k3Gamma
/gate/source/capillary28mm/setPositronInteractions kParaPs kDirect kDirect kOrthoPs kOrthoPs
/gate/source/capillary28mm/setPromptPhotonProbabilites 1 1 1 1 1
/gate/source/capillary28mm/setPromptPhotonEnergies 1.274 1.274 1.274 1.274 1.274 MeV
/gate/source/capillary28mm/gps/particle       gamma

/gate/source/addSource                        capillary37mm PositroniumSource
/gate/source/capillary37mm/gps/pos/centre         5.72 0. 8.175 cm
/gate/source/capillary37mm/gps/pos/type           Volume
/gate/source/capillary37mm/gps/pos/shape          Cylinder
/gate/source/capillary37mm/gps/pos/radius         0.25 cm
/gate/source/capillary37mm/gps/pos/halfz          2.525 cm
/gate/source/capillary37mm/setActivity    1289.0 Bq
/gate/source/capillary37mm/setType Ps
/gate/source/capillary37mm/setPositroniumFractions 0.092 0.76095 0.00205 0.14291 0.00209
/gate/source/capillary37mm/setPositroniumLifetimes 0.15 0.44 0.44 2.04 2.04 ns
/gate/source/capillary37mm/setDecayKinds k2Gamma k2Gamma k3Gamma k2Gamma k3Gamma
/gate/source/capillary37mm/setPositronInteractions kParaPs kDirect kDirect kOrthoPs kOrthoPs
/gate/source/capillary37mm/setPromptPhotonProbabilites 1 1 1 1 1
/gate/source/capillary37mm/setPromptPhotonEnergies 1.274 1.274 1.274 1.274 1.274 MeV
/gate/source/capillary37mm/gps/particle       gamma

/gate/source/list

/gate/output/analysis/disable  
/gate/output/fastanalysis/disable  
/gate/output/multianalysis/enable

/gate/output/root/enable
/gate/output/root/setFileName ../output/simulation_output-1

/gate/output/root/setRootHitFlag 1
/gate/output/root/setRootSinglesFlag 1

/gate/output/multianalysis/verbose 1  
/gate/output/multianalysis/describe

/gate/random/setEngineName JamesRandom
/gate/random/setEngineSeed 426405530

/gate/random/verbose 1

/gate/application/setTimeSlice   1.0 s
/gate/application/setTimeStart   0 s
/gate/application/setTimeStop    1.0 s
/gate/application/startDAQ

