/gate/physics/addProcess PhotoElectric gamma
/gate/physics/processes/PhotoElectric/setModel LivermoreModel

/gate/physics/addProcess Compton gamma
/gate/physics/processes/Compton/setModel LivermorePolarizedModel

/gate/physics/processList Enabled
/gate/physics/processList Initialized

/gate/physics/Gamma/SetCutInRegion world 10 mm
/gate/physics/Electron/SetCutInRegion world 10 mm
/gate/physics/Positron/SetCutInRegion world 10 mm

/gate/physics/displayCuts